### ISSUE TITLE
Issue on log in with form validation

### ISSUE THREAD

**Issue by gyoder** [sourque/minos#6]
When attempting to start up a server and log in I was getting the following message.
```2023-01-31 17:08:37,925] ERROR in app: Exception on /login [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/opt/minos/engine/./server.py", line 462, in login
    if form.validate_on_submit():
  File "/usr/local/lib/python3.8/dist-packages/flask_wtf/form.py", line 86, in validate_on_submit
    return self.is_submitted() and self.validate(extra_validators=extra_validators)
TypeError: validate() got an unexpected keyword argument 'extra_validators'
```
Going into `/opt/minos/engine/server.py` and changing `if form.validate_on_submit():` to `if True:` fixed the issue for me and works for what I need to do with it but that does remove authentication from the login which is not ideal. Just putting this here if anyone needs to know. This was running on a Ubuntu 20.04 docker container

**Comment by sourque** [comment]
This looks like it's probably from https://github.com/wtforms/flask-wtf/issues/547. We could remove the optional parameter bit and just pass it as a positional one, or since we didn't pin packages (oops), make sure to use flask-wtf `1.1.0` or an older version which I believe works.
